// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6F76nlo7m7UvanQUSuxjSfvnEEz1En4',
    appId: '1:535559477740:web:17ca53ef0729af4a5608c9',
    messagingSenderId: '535559477740',
    projectId: 'reunify-3eef3',
    authDomain: 'reunify-3eef3.firebaseapp.com',
    storageBucket: 'reunify-3eef3.appspot.com',
    measurementId: 'G-N5JK84DQFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKUwKWAqfFMCzyWmCABEeKXUpTH2EjvCs',
    appId: '1:535559477740:android:7cfa0bef15a8de445608c9',
    messagingSenderId: '535559477740',
    projectId: 'reunify-3eef3',
    storageBucket: 'reunify-3eef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZl2wTgL4MrHWiWPe4gTTVtxN_hhAsmK4',
    appId: '1:535559477740:ios:b54a0c212d846c0c5608c9',
    messagingSenderId: '535559477740',
    projectId: 'reunify-3eef3',
    storageBucket: 'reunify-3eef3.appspot.com',
    iosBundleId: 'com.example.reunify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZl2wTgL4MrHWiWPe4gTTVtxN_hhAsmK4',
    appId: '1:535559477740:ios:b54a0c212d846c0c5608c9',
    messagingSenderId: '535559477740',
    projectId: 'reunify-3eef3',
    storageBucket: 'reunify-3eef3.appspot.com',
    iosBundleId: 'com.example.reunify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf6F76nlo7m7UvanQUSuxjSfvnEEz1En4',
    appId: '1:535559477740:web:e1c4a320bab446445608c9',
    messagingSenderId: '535559477740',
    projectId: 'reunify-3eef3',
    authDomain: 'reunify-3eef3.firebaseapp.com',
    storageBucket: 'reunify-3eef3.appspot.com',
    measurementId: 'G-4DV8MC88K5',
  );

}